name: Test Building Code
# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]
# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out Repository Code
        uses: actions/checkout@v3
      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build Repository Code
        run: |
          cd ui
          npm install
          npm run build
          cd client 
          npm install
          cd ..
          npm run start
